name: Publish package to GitHub Packages
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v
        with:
          java-version: '11'
          distribution: 'adopt'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Publish package
        run: mvn --batch-mode deploy --stack-name sam-hello-world --s3-bucket mybucketsmirnov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}